export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const CREATE_USER= "CREATE_USER";
export const UPDATE_USER= "UPDATE_USER";
export const DELETE_USER= "DELETE_USER";
export const GET_USER= "GET_USER";
export const GET_USERS="GET_USERS";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const PROJECT_LOADING = "PROJECT_LOADING";
export const GET_PROJECTS = "GET_PROJECTS";
export const PROJECTS_LOADING = "PROJECTS_LOADING";


export const CREATE_TEAM = "CREATE_TEAM";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const GET_TEAM = "GET_TEAM";
export const TEAM_LOADING = "TEAM_LOADING";
export const GET_TEAMS = "GET_TEAMS";
export const TEAMS_LOADING = "TEAMS_LOADING";

export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const GET_EVENT = "GET_EVENT";
export const EVENT_LOADING = "EVENT_LOADING";
export const GET_EVENTS = "GET_EVENTS";
export const EVENTS_LOADING = "EVENTS_LOADING";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ATTENDEE_LOADING = "ATTENDEE_LOADING";
export const STAGE_ATTENDEE = "STAGE_ATTENDEE";
export const STAGE_ATTENDEES = "STAGE_ATTENDEES";
export const UNSTAGE_ATTENDEE = "UNSTAGE_ATTENDEE";
export const UNSTAGE_ATTENDEES = "UNSTAGE_ATTENDEES";
export const ATTENDEE_NOT_FOUND = "ATTENDEE_NOT_FOUND";


export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';